/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import dto.InstitucionNuevaDTO;
import dto.InstitucionRegistradaDTO;
import dto.ReporteDTO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.itson.diseno.subsistemaagregarinstitucion.FacadeAgregarInstitucion;
import org.itson.diseno.subsistemaagregarinstitucion.IFacadeAgregarInstitucion;
import org.itson.diseño.levantarreportess.FacadeLevantarReporte;
import org.itson.diseño.levantarreportess.IFacadeLevantarReporte;

/**
 *
 * @author castr
 */
public final class FrmSeleccionInstitucion extends javax.swing.JFrame {

    private final IFacadeAgregarInstitucion facadeAgregarInstitucion;
    private IFacadeLevantarReporte facadeLevantarReporte;
    private String institucion;
    private String funcionInstitucion;
    private String nombreInstitucion;
    private ReporteDTO reporteDTO;
    private List<InstitucionNuevaDTO> institucionesnuevas;
    private List<InstitucionRegistradaDTO> instituciones;
    private InstitucionRegistradaDTO institucionSeleccionada;
    private ControlNavegacion controladores;

    /**
     * Creates new form FrmSeleccionInstitucion
     *
     * @param facadeLevantarReporte
     */
    public FrmSeleccionInstitucion() {
        initComponents();
        this.facadeAgregarInstitucion = new FacadeAgregarInstitucion();
        this.facadeLevantarReporte = new FacadeLevantarReporte();
        institucionesnuevas = facadeLevantarReporte.obtenerInstituciones();
        this.controladores = new ControlNavegacion();
        this.instituciones = facadeAgregarInstitucion.consultarInstituciones();
        controladores = new ControlNavegacion();
        llenarComboBox();
    }

    private void llenarComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (InstitucionRegistradaDTO institucion : instituciones) {
            String nombreInstitucion = institucion.getNombre();
            String siglasInstitucion = institucion.getSiglas();
            if (siglasInstitucion != null && !siglasInstitucion.isEmpty()) {
                model.addElement(siglasInstitucion);
            } else {
                model.addElement(nombreInstitucion);
            }
        }
        cboSeleccionInstitucion.setModel(model);
    }

    private void seleccionarSiguiente() {
        if (institucionSeleccionada != null) {
            if (reporteDTO == null) {
                reporteDTO = new ReporteDTO();
            }
            reporteDTO.setInstitucion(institucionSeleccionada);
            controladores.mostrarSeleccionIncidentes(reporteDTO);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se selecciono ninguna institucion", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblInformacionInstitucion = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAvances = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        cboSeleccionInstitucion = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblContenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paso 1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 450, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_gobierno_mexico.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        lblDescripcion1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblDescripcion1.setForeground(new java.awt.Color(110, 110, 110));
        lblDescripcion1.setText("Seleccione entre las instituciones disponibles las cuales considere son las indicadas para darle ");
        jPanel1.add(lblDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 510, 20));

        lblDescripcion2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblDescripcion2.setForeground(new java.awt.Color(110, 110, 110));
        lblDescripcion2.setText("seguimiento al reporte.");
        jPanel1.add(lblDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 500, 20));

        lblInformacionInstitucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblInformacionInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 500, -1));

        btnVolver.setBackground(new java.awt.Color(229, 229, 229));
        btnVolver.setFont(new java.awt.Font("Inter Light", 0, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(181, 18, 57));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 18, 57)));
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 110, 40));

        btnAvances.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        btnAvances.setForeground(new java.awt.Color(255, 255, 255));
        btnAvances.setText("Avances");
        btnAvances.setBorder(null);
        btnAvances.setContentAreaFilled(false);
        btnAvances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvances, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(229, 229, 229));
        btnSiguiente.setFont(new java.awt.Font("Inter Light", 0, 16)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(181, 18, 57));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 18, 57)));
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 110, 40));

        btnHistorial.setFont(new java.awt.Font("Inter Light", 0, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Historial");
        btnHistorial.setBorder(null);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        cboSeleccionInstitucion.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        cboSeleccionInstitucion.setForeground(new java.awt.Color(33, 33, 33));
        cboSeleccionInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSeleccionInstitucionActionPerformed(evt);
            }
        });
        jPanel1.add(cboSeleccionInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, 40));

        lblTitulo.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(33, 33, 33));
        lblTitulo.setText("Instituciones correspondientes");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblHeader.setBackground(new java.awt.Color(10, 50, 6));
        lblHeader.setOpaque(true);
        jPanel1.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 80));

        lblContenido.setBackground(new java.awt.Color(255, 255, 255));
        lblContenido.setOpaque(true);
        jPanel1.add(lblContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboSeleccionInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSeleccionInstitucionActionPerformed
        String seleccion = (String) cboSeleccionInstitucion.getSelectedItem();
        institucionSeleccionada = null;
        for (InstitucionRegistradaDTO institucion : instituciones) {
            if (seleccion.equals(institucion.getSiglas()) || seleccion.equals(institucion.getNombre())) {
                institucionSeleccionada = institucion;
                break;
            }
        }
    }//GEN-LAST:event_cboSeleccionInstitucionActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        seleccionarSiguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAvancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancesActionPerformed
        controladores.mostrarPortalInstituciones();
        dispose();
    }//GEN-LAST:event_btnAvancesActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        controladores.mostrarHistorial();
        dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        controladores.mostrarMenuPrincipal();
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvances;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboSeleccionInstitucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContenido;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInformacionInstitucion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
